[package]
name    = "lp-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "lifeplanner"
path = "src/main.rs"

[dependencies]
lp-core   = { path = "../lp-core" }
tokio     = { workspace = true }
clap      = { version = "4", features = ["derive"] }
chrono    = { workspace = true }
